AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM template for Mandelbrot image generation.

Globals:
  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'content-type'"
      AllowOrigin: "'*'"
      AllowCredentials: "'*'"
  Function:
    Architectures:
      - arm64
    Timeout: 60

Resources:
  PlotFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: "A lambda that plots the Mandelbrot set."
      PackageType: Image
      Events:
        Plot:
          Type: Api
          Properties:
            Path: /plot
            Method: post
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./functions/plot

Outputs:
  PlotApi:
    Description: "API Gateway endpoint URL for Mandelbrot function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/plot"
